# coding: utf-8

"""
    REST APIs for UT runner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UnitTesterJobReadResp(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'str',
        'status': 'str',
        'created_at': 'str',
        'last_updated_at': 'str',
        'last_update': 'str'
    }

    attribute_map = {
        'job_id': 'job_id',
        'status': 'status',
        'created_at': 'created_at',
        'last_updated_at': 'last_updated_at',
        'last_update': 'last_update'
    }

    def __init__(self, job_id=None, status='scheduled', created_at=None, last_updated_at=None, last_update=None):  # noqa: E501
        """UnitTesterJobReadResp - a model defined in Swagger"""  # noqa: E501

        self._job_id = None
        self._status = None
        self._created_at = None
        self._last_updated_at = None
        self._last_update = None
        self.discriminator = None

        if job_id is not None:
            self.job_id = job_id
        if status is not None:
            self.status = status
        if created_at is not None:
            self.created_at = created_at
        if last_updated_at is not None:
            self.last_updated_at = last_updated_at
        if last_update is not None:
            self.last_update = last_update

    @property
    def job_id(self):
        """Gets the job_id of this UnitTesterJobReadResp.  # noqa: E501

        Unique ID of the job  # noqa: E501

        :return: The job_id of this UnitTesterJobReadResp.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this UnitTesterJobReadResp.

        Unique ID of the job  # noqa: E501

        :param job_id: The job_id of this UnitTesterJobReadResp.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def status(self):
        """Gets the status of this UnitTesterJobReadResp.  # noqa: E501

        Current status of the job  # noqa: E501

        :return: The status of this UnitTesterJobReadResp.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UnitTesterJobReadResp.

        Current status of the job  # noqa: E501

        :param status: The status of this UnitTesterJobReadResp.  # noqa: E501
        :type: str
        """
        allowed_values = ["scheduled", "running", "successful", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def created_at(self):
        """Gets the created_at of this UnitTesterJobReadResp.  # noqa: E501

        Time at which job was created  # noqa: E501

        :return: The created_at of this UnitTesterJobReadResp.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this UnitTesterJobReadResp.

        Time at which job was created  # noqa: E501

        :param created_at: The created_at of this UnitTesterJobReadResp.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def last_updated_at(self):
        """Gets the last_updated_at of this UnitTesterJobReadResp.  # noqa: E501

        Time at which the job was updated  # noqa: E501

        :return: The last_updated_at of this UnitTesterJobReadResp.  # noqa: E501
        :rtype: str
        """
        return self._last_updated_at

    @last_updated_at.setter
    def last_updated_at(self, last_updated_at):
        """Sets the last_updated_at of this UnitTesterJobReadResp.

        Time at which the job was updated  # noqa: E501

        :param last_updated_at: The last_updated_at of this UnitTesterJobReadResp.  # noqa: E501
        :type: str
        """

        self._last_updated_at = last_updated_at

    @property
    def last_update(self):
        """Gets the last_update of this UnitTesterJobReadResp.  # noqa: E501

        Latest update message for the job  # noqa: E501

        :return: The last_update of this UnitTesterJobReadResp.  # noqa: E501
        :rtype: str
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this UnitTesterJobReadResp.

        Latest update message for the job  # noqa: E501

        :param last_update: The last_update of this UnitTesterJobReadResp.  # noqa: E501
        :type: str
        """

        self._last_update = last_update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnitTesterJobReadResp, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnitTesterJobReadResp):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
