# coding: utf-8

"""
    REST APIs for UT runner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.unit_tester_error500 import UnitTesterError500  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitTesterError500(unittest.TestCase):
    """UnitTesterError500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnitTesterError500(self):
        """Test UnitTesterError500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.unit_tester_error500.UnitTesterError500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
