# coding: utf-8

"""
    REST APIs for UT runner

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.unit_tester_api import UnitTesterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUnitTesterApi(unittest.TestCase):
    """UnitTesterApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.unit_tester_api.UnitTesterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job(self):
        """Test case for get_job

        Get the status of a job.  # noqa: E501
        """
        pass

    def test_post_job(self):
        """Test case for post_job

        Start running the UT for a given application  # noqa: E501
        """
        pass

    def test_post_job_log_export(self):
        """Test case for post_job_log_export

        Export a tar.gz archive with log files for the job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
